# Site settings
title: Conso App 2.0
description: Faîtes des économies et mangez mieux comme jamais auparavant !
cover: assets/images/map.png
logo: assets/images/logo.png
favicon: assets/images/logo.png
about: assets/images/about_image.png
list: assets/images/list.png
contribution1: assets/images/contribution1.png
contribution2: assets/images/contribution2.png
contribution3: assets/images/contribution3.png
contribution4: assets/images/contribution4.png

baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://apinot.github.io/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
github: felixleo22/ConsoApp
trello: 5nHUSyxK/consoapp


permalink: /:title

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
branch: master #branch

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
